### ISSUE TITLE
Doesn't work with `consistent-type-imports` rule

### ISSUE THREAD

**Issue by Gryfit** [SeinopSys/eslint-plugin-import-newlines#2]
It's either a bug or I'm doing something wrong.
When type-only imports are enforced, the code should format to this:
```ts
import type {
  Type1,
  Type2,
} from '../index.ts';
import {
  Component1,
  Component2,
} from '../index.ts';
```
But it gets merged and creates this thing:
```ts
import {
Component1,
Component2,
,
Type1,
Type2,
} from '../index.ts';

**Comment by SeinopSys** [comment]
Apologies for the radio silence, I had notification muted for this repository for some odd reason. I will be looking into this issue, someone else also prepared a PR that might help with this.

**Comment by SeinopSys** [comment]
I believe with version `1.1.4` (which I have just released) this should now be fixed, please update to this version, and if the problem still persists, reopen the issue with any additional details.
