### ISSUE TITLE
add a tab character after each line import

### ISSUE THREAD

**Issue by hieunm22** [SeinopSys/eslint-plugin-import-newlines#3]
as title, I detect an issue that every import/export doesn't add a tab character after each line import/export, and a new line character before the curly close bracket. this looks better than current

```ts
// original
import { method1, method2, method3, method4 } from 'alphabet'

// format
import { method1,
method2,
method3,
method4 } from 'alphabet'

// expected
import {  // add a new line character after {
  method1,  // tab character at the beginning of line
  method2,
  method3,
  method4
} from 'alphabet'
```
could you do a little fix for it
Thanks

**Comment by SeinopSys** [comment]
Hi, this is mentioned in the README:
 > Note that the plugin simply inserts newline characters after each token in the import when splitting, and the fix output never includes leading tabs or spaces. To have consistent indentation, be sure to use the built-in `indent` rule.

You can find how to configure said rule here: https://eslint.org/docs/rules/indent
