### ISSUE TITLE
Supress check for mustNotSplit 

### ISSUE THREAD

**Issue by m1lk1way** [SeinopSys/eslint-plugin-import-newlines#8]
Hi, i've played a bit with configuration and didn't find a way to add only check for N characters length to break imports. My requirement is to let pass both
```import {a, b} from "c"```
and
```
import {
    a,
    b,
} from "c"
```
in case if import string length is less than configured value.
What could be the solution?

**Comment by SeinopSys** [comment]
Please upgrade to version 1.2.0 and set the new `forceSingleLine` config option to `false`. This should allow for the behaviour you described. If you run into any problems, please feel free to reopen the issue.

**Comment by m1lk1way** [comment]
Thx a lot 🚀
